# Generated by Django 3.1.5 on 2021-01-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210128_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknumber',
            name='isbn_13',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
